# Generated by Django 5.1.3 on 2024-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='user_images/default_avatar.png', help_text='Изображение размером не более 5 мб', null=True, upload_to='user_images/'),
        ),
    ]
