# Generated by Django 5.1.3 on 2024-12-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'permissions': [('can_view_all_users', 'Can view all users'), ('can_block_user', 'Can block user')]},
        ),
    ]
