# Generated by Django 5.1.3 on 2024-12-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_change_user', 'Can change user')]},
        ),
    ]
