# Generated by Django 5.1.3 on 2024-11-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent', models.DateTimeField(auto_now=True, verbose_name='Дата старта')),
                ('last_sent', models.DateTimeField(auto_now=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('closed', 'Завершена')], default='created', max_length=7, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='sender.message')),
                ('recipients', models.ManyToManyField(related_name='newsletters', to='sender.recipient')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['first_sent'],
            },
        ),
    ]
