# Generated by Django 5.1.3 on 2024-12-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_mailingattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='exc_state',
            field=models.CharField(choices=[('success', 'Успешно'), ('error', 'Не успешно')], default='error', max_length=15, verbose_name='Статус отправки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='server_response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
