# Generated by Django 5.1.3 on 2024-12-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_alter_mailingattempt_exc_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='first_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
