# Generated by Django 5.1.3 on 2024-12-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_newsletter_owner_recipient_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['-id'], 'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
    ]
