# Generated by Django 5.1.3 on 2024-12-17 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_alter_mailingattempt_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email'], 'permissions': [('can_delete_recipient', 'Can delete recipient'), ('can_view_recipients', 'Can view recipients')], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Добавлен'),
        ),
    ]
